server:
  port: 8080
spring:
  application:
    name: "back-agrocredito-core"
  banner:
    charset: utf-8
    location: "banner.txt"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "123456"
    url: "jdbc:mysql://localhost:3306/agrocredito"
  security:
    user:
      name: user
      password: password

security:
  jwt:
    secret-key: "McvbIKwPaVjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9VUvAWw7GzFMV6ZhHsI"
    expiration: 86400000
    refresh-token:
      expiration: 604800000